### ISSUE TITLE
Subscription report interval [0, 2]

### ISSUE THREAD

**Issue by caipiblack** [home-assistant-libs/python-matter-server#1128]
Hello,

I have made an ICD device using ESP32C6 and ICD example from esp-matter.

I have nice results power usage results (idle voltage is very low (uA)

But there is some issue with the subscription report interval. There is a report every 2 seconds and it increase drastically the average battery usage.

```
2025-04-10 20:17:10.448 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Subscription succeeded with report interval [0, 2]
```

But I don't understand how it is posssible, I am using: `ghcr.io/home-assistant-libs/python-matter-server:stable` so it should be 7.0.1

But when I look the code of 7.0.1 (stable) it seems that the max interval can only be 60 or 600 seconds, so how it's possible that I have '2' ?

My docker-compose:

```
services:
  # python-matter-server
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    # If you adjust command line, make sure to pass the default CMD arguments too:
    command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0 --log-level-sdk detail
```

The SHA256 of my image match with 7.0.1: 828c1cd3f957bb0287a099a439505457a25f5d65ed34281acf19cfbf537fe346
```
$ docker image inspect 3bdb7bee287b
[
    {
        "Id": "sha256:3bdb7bee287bfc5fed3bfb2fe0a115cc1d50e7cd725f4638a3c3e3daed49d32e",
        "RepoTags": [
            "ghcr.io/home-assistant-libs/python-matter-server:stable"
        ],
        "RepoDigests": [
            "ghcr.io/home-assistant-libs/python-matter-server@sha256:828c1cd3f957bb0287a099a439505457a25f5d65ed34281acf19cfbf537fe346"
        ],
....
```

The code in `device_controller.py`:

```
        if routing_role is None:
            interval_ceiling = NODE_SUBSCRIPTION_CEILING_WIFI
        elif (
            routing_role
            == Clusters.ThreadNetworkDiagnostics.Enums.RoutingRoleEnum.kSleepyEndDevice
        ):
            interval_ceiling = NODE_SUBSCRIPTION_CEILING_BATTERY_POWERED
        else:
            interval_ceiling = NODE_SUBSCRIPTION_CEILING_THREAD
        if node.attributes.get(ICD_ATTR_LIST_ATTRIBUTE_PATH) is not None:
            # for ICD devices, the interval floor must be 0 according to the spec,
            # to prevent additional battery drainage. See Matter core spec, chapter 8.5.2.2.
            # TODO: revisit this after Matter 1.4 release (as that mighht change this again).
            interval_floor = NODE_SUBSCRIPTION_FLOOR_ICD
        else:
            interval_floor = NODE_SUBSCRIPTION_FLOOR_DEFAULT
        self._resubscription_attempt[node_id] = 0
        # set-up the actual subscription
        sub: Attribute.SubscriptionTransaction = (
            await self._chip_device_controller.read_attribute(
                node_id,
                [()],
                events=[("*", 1)],
                return_cluster_objects=False,
                report_interval=(interval_floor, interval_ceiling),
                auto_resubscribe=True,
            )
        )

        # Make sure to clear default handler which prints to stdout
        sub.SetAttributeUpdateCallback(None)
        sub.SetRawAttributeUpdateCallback(attribute_updated_callback_threadsafe)
        sub.SetEventUpdateCallback(event_callback_threadsafe)
        sub.SetErrorCallback(error_callback)
        sub.SetResubscriptionAttemptedCallback(resubscription_attempted)
        sub.SetResubscriptionSucceededCallback(resubscription_succeeded)

        node.available = True
        # update attributes with current state from read request
        tlv_attributes = sub.GetTLVAttributes()
        node.attributes.update(parse_attributes_from_read_result(tlv_attributes))

        report_interval_floor, report_interval_ceiling = (
            sub.GetReportingIntervalsSeconds()
        )
        node_logger.info(
            "Subscription succeeded with report interval [%d, %d]",
            report_interval_floor,
            report_interval_ceiling,
        )
```

I don't understand why the max interval of the subscribe is "2".
