### ISSUE TITLE
DNSSD packet parsing failed

### ISSUE THREAD

**Issue by ljmerza** [home-assistant-libs/python-matter-server#307]
im runing latest matter version on a raspberry pi 3 and i keep getting these errors over and over

```
2023-05-31T13:43:40.424133653Z 2023-05-31 09:43:40 z3 chip.DIS[1] ERROR DNSSD packet parsing failed (for SRV records)
2023-05-31T13:43:40.424263809Z 2023-05-31 09:43:40 z3 chip.DIS[1] ERROR DNSSD packet parsing failed (for non-srv records)
```

docker compose on latest master branch

```
matter:
    platform: linux/arm64/v8
    build:
      context: ./python-matter-server
      dockerfile: Dockerfile.dev
    container_name: matter
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./volumes/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
 ```
