### ISSUE TITLE
getting error: exec /usr/local/bin/matter-server: exec format error

### ISSUE THREAD

**Issue by ljmerza** [home-assistant-libs/python-matter-server#420]
```
matter:
    platform: linux/arm64
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter
    restart: unless-stopped
    env_file: ./env/global.env
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./volumes/matter/data:/data/
      - /run/dbus:/run/dbus:ro
```

```
uname -m
x86_64
```

```
cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
