### ISSUE TITLE
production server detection shall be enhanced

### ISSUE THREAD

**Issue by waclaw66** [home-assistant-libs/python-matter-server#913]
Production server detection doesn't cover following use case.

- Home Assistant Container
- python-matter-server running in Docker
- custom ingress (HACS hass_ingress) configuration:
`/var/lib/homeassistant/ingress/matter_server.yaml`
```yaml
require_admin: true
ui_mode: toolbar
title: Matter Server
icon: mdi:puzzle
url: http://127.0.0.1:5580
```

![obrazek](https://github.com/user-attachments/assets/643f21fa-e5e0-449e-8429-fabb83d98267)

Production server detection fails then because it's requiring either of these two conditions that are not fulfilled because `lovelylain/hass_ingress` is building ingress URL like `/api/ingress/[app_name]`.

I would suggest to add another condition `location.href.includes("/api/ingress/")`.

Thanks in advance.
