### ISSUE TITLE
A working Matter docker container in a macvlan network, am I in for trouble later?

### ISSUE THREAD

**Issue by kelvtech-co-uk** [home-assistant-libs/python-matter-server#983]
Have spent the last day+ getting my first Matter device working, a Nuki Smart Lock Pro 4.0.  I don't run any other containers with `network_mode=host` so wanted to avoid it.

My HA is a docker container with a macvlan network attached.  I found this repo quickly whilst reading the docs on how to setup Matter.  My container host is an unraid server which has `net.ipv6.conf.iface.forwarding=1` by default which I left unchanged.  I updated `.accept_ra=2` and `.accept_ra_rt_info_max_plen=64` as per the readme here and a few other posts and articles I found.  My Thread network is running off a Google Nest Hub, I made sure HA knew about this and that HA, Matter and the Nest Hub are all in the same IPv4 subnet.  After the changes mentioned my unraid server saw an IPv6 route via my Google Nest Hub which I took as a positive sign.

On the Matter container side I made the same changes as per the host but additionally I set `net.ipv6.conf.eth0.forwarding=1`.  This then enabled my Matter container to successfully establish a secure connection to the Nuki lock and complete provisioning directly into HA.  I can sometimes take some minutes for the routes to fully populate, think my worst case was 15 minutes or typically its much quicker.

Given I haven't found any other reference to this, coulped with my lack of experience with IPv6 networking and Matter in general I'm concerned that whilst everything seems stable and functional that I may have issues in the future.  I'd appreicate any critique of my solution here to better educate me as necessary.

```
  matter:
    container_name: matter
    hostname: matter
    restart: unless-stopped
    networks:
      mynetwork:
        ipv4_address: 192.168.1.25
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/cache/docker/infrastructure_apps/matter/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://healthchecks.mylocaldomain:8015/ping/bebed870-47c2-4957-bb84-1e78d11ae838"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    sysctls:    # Necessary for the container to receive the routes from the remote Thread network managed by my Google Nest Hub.
      net.ipv6.conf.eth0.accept_ra: 2
      net.ipv6.conf.eth0.accept_ra_rt_info_max_plen: 64
      net.ipv6.conf.eth0.forwarding: 1
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
```

**Comment by marcelveldt** [comment]
Running Matter server in docker is unsupported and completely at your own risk. We provide a docker image just to be helpul for those willing to take the plunge to make it working but we do not provide any support here, sorry.

**Comment by SisyphusMD** [comment]
Hi @kelvtech-co-uk, I’m also interested in running the matter server docker container without host mode, specifically because I have my HA docker container in a macvlan (to allow it to be a part of various other bridge networks as well).

I was wondering if you have it working? Following your comment here and those from issue #347, I have the following docker compose file:

```
networks:

  macvlan3:
    external: true

services:

  matter:
    container_name: matter
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    volumes:
      - ./volumes/matter:/data
      - /run/dbus:/run/dbus:ro # Required for Bluetooth via dbus
    # network_mode: host # Required for mDNS to work
    security_opt:
      - apparmor:unconfined # Required for Bluetooth via dbus
    sysctls:
      net.ipv6.conf.eth0.accept_ra_rt_info_max_plen: 64
    networks:
      macvlan3:
        ipv4_address: 192.168.3.8
```

And this is the command used to create the macvlan3 network:

`docker network create -d macvlan -o parent=enp0s13f0u3 --subnet 192.168.3.0/24 --gateway 192.168.3.1 macvlan3`

It works great initially, connects to my Aqara Hub M2, and gives HA control of various devices connected. The logs give some errors, but they don’t seem to effect function at first:

```
matter  | 2025-01-01 17:49:04.369 (MainThread) INFO [matter_server.server.device_controller] Starting Matter commissioning with code using Node ID 1.
matter  | 2025-01-01 17:49:04.372 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:49:04.373 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/controller/SetUpCodePairer.cpp:332
matter  | 2025-01-01 17:49:04.877 (Dummy-2) INFO [chip.ChipDeviceCtrl] Established secure session with Device
matter  | 2025-01-01 17:49:06.164 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:49:06.164 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:49:06.873 (Dummy-2) INFO [chip.ChipDeviceCtrl] Commissioning complete
matter  | 2025-01-01 17:49:06.874 (MainThread) INFO [matter_server.server.device_controller] Commissioned Node ID: 1 vs 1
matter  | 2025-01-01 17:49:06.874 (MainThread) INFO [matter_server.server.device_controller] Matter commissioning of Node ID 1 successful.
matter  | 2025-01-01 17:49:06.874 (MainThread) INFO [matter_server.server.device_controller] Interviewing node: 1
matter  | 2025-01-01 17:49:07.200 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Setting-up node...
matter  | 2025-01-01 17:49:07.201 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Setting up attributes and events subscription.
matter  | 2025-01-01 17:49:07.299 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Subscription succeeded with report interval [1, 60]
matter  | 2025-01-01 17:49:07.300 (MainThread) INFO [matter_server.server.device_controller] Commissioning of Node ID 1 completed.
```

Unfortunately, the function does not survive matter container restart. I see these errors after restarting the container:

```
matter  | 2025-01-01 17:53:09.516 (MainThread) INFO [matter_server.server.device_controller.mdns] <Node:1> Discovered on mDNS
matter  | 2025-01-01 17:53:09.517 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Setting-up node...
matter  | 2025-01-01 17:53:09.719 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:09.719 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:09.721 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:09.722 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:09.725 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:09.725 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:09.727 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:09.727 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:09.729 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:09.729 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:10.521 (MainThread) INFO [matter_server.server.device_controller.mdns] <Node:1> Discovered on mDNS
matter  | 2025-01-01 17:53:12.733 (MainThread) INFO [matter_server.server.sdk] <Node:1> Attempting to establish CASE session... (attempt 2 of 2)
matter  | 2025-01-01 17:53:12.936 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:12.936 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:12.938 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:12.938 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:12.941 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:12.941 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:12.942 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:12.943 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:12.946 (Dummy-2) CHIP_ERROR [chip.native.IN] SendMessage() to UDP:[fe80::1ac2:3cff:fe14:e0c8%eth0]:5540 failed: src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable
matter  | 2025-01-01 17:53:12.946 (Dummy-2) CHIP_ERROR [chip.native.-] src/inet/UDPEndPointImplSockets.cpp:421: OS Error 0x02000065: Network is unreachable at src/app/OperationalSessionSetup.cpp:254
matter  | 2025-01-01 17:53:12.946 (MainThread) WARNING [matter_server.server.device_controller] <Node:1> Setup for node failed: Unable to establish CASE session with Node 1
matter  | 2025-01-01 17:53:12.946 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Retrying node setup in 60 seconds...
```

Any idea what’s going on here? I appreciate any insights you can provide!

**Comment by kelvtech-co-uk** [comment]
Hi, yes mines working fine and persists through restarts of the container and container host.

At a quick glance I'd say your matter container isn't learning the routes for your Thread network until some time has past. You could watch this yourself by connecting to the containers shell and issue an 'ip -6 route' command. You're looking for the learned route advertised by your Thread Border Router, this for me is learnt quite quickly but in my research others were citing a 10+ minute lag in the container starting and these routes being learnt. Basically keep issuing that same command into the containers shell until you see the route needed. After the route is their then the network errors in your log should cease.

Let me know if this isn't making sense and I'll post back more details later tonight/tomorrow.

**Comment by SisyphusMD** [comment]
Thanks for all of that! Okay so I tried again, but still get nothing returned for ‘ip -6 route’ in the matter container, even after about 20 minutes. And ‘ip -6 address’ only shows me having an inet6 on my loopback address, but not on the container’s eth0.

I then tried adding an ipv6 subnet and gateway to my macvlan network, and assigned an ipv6 address to the container, but still don’t seem to have an ipv6 address on my container’s eth0 and no ‘ip -6 route’ populated. Is this pointing to a different problem? Maybe docker not appropriately utilizing ipv6 for this container?

**Comment by SisyphusMD** [comment]
Well I’m happy to say the issue is resolved. You were right that routes weren’t being learned. I didn’t realize that macvlan networks in docker don’t have ipv6 enabled by default, and you have to explicitly enable ipv6 when creating the network. In case anyone ends up here via search, my network creation command was this:

`docker network create -d macvlan -o parent=enp0s13f0u3 --ipv6 --subnet 192.168.3.0/24 --gateway 192.168.3.1 macvlan3 `

Thanks for all your help @kelvtech-co-uk !

**Comment by Apollon77** [comment]
@SisyphusMD @kelvtech-co-uk Would it be possible to post a "how to setup macvlan" as a step by step guide also for other users?

**Comment by kelvtech-co-uk** [comment]
> @SisyphusMD @kelvtech-co-uk Would it be possible to post a "how to setup macvlan" as a step by step guide also for other users?

macvlan networks are a docker construct and have usecases beyond Matter.  I'd recommend starting with the docker docs on how to [define](https://docs.docker.com/engine/network/drivers/macvlan/) a macvlan network as well as either the [compose](https://docs.docker.com/reference/compose-file/services/#networks) or [run](https://docs.docker.com/engine/network/) references for creating containers that use them.

There are further implications involved so its worth while to read up and experiment and maybe start with something that is simpler i.e. that doesn't require IPv6 and integrating a Thread network.  This is why my initial issue ticket was shutdown from the start as its a bit of a mine field and so using the host network just makes this a simpler implementation albeit with some caveats.

**Comment by jollyjinx** [comment]
I got it working with the following configuration but only with docker-compose as that allows sysctls on the vlan interface
my biggest hurdle was that I was using command: "--log-level debug" but that stored the config in /root/ inside the docker container , so every time i recreated the container it would no longer work.
Furthermore the root interface on the vlan is set to ipv6 forwarding 0 and accept_ra_rt_info_max_plen 64 as well.


```  
. . . .
matter:
    mac_address: CA-FE-BA-BE-00-0C
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    command: "--storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0 --log-level debug"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - PUID=${UID}
      - PGID=${GID}
    user: "${UID:-1000}:${GID:-1000}"
    security_opt:
      - apparmor:unconfined
    sysctls:
      net.ipv6.conf.eth0.accept_ra: 1
      net.ipv6.conf.eth0.accept_ra_rt_info_max_plen: 64
    volumes:
      - ${DOCKER_HOME}/matter/data:/data/
    ports:
      - 5580:5580
    networks:
      mqtt-net: {}
      aservice1000: 
        ipv4_address: ${NETWORK_PREFIX}.0.13
    depends_on:
      - homeassistant

networks:
  aservice1000:
    driver: macvlan
    driver_opts:
      parent: vlan.1000
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX}.0.0/24
          gateway: ${NETWORK_PREFIX}.0.1
        - subnet: fe80:0::/64
          gateway: fe80::1
    enable_ipv6: true
. . . .

```

**Comment by kelvtech-co-uk** [comment]
> I got it working with the following configuration but only with docker-compose as that allows sysctls on the vlan interface my biggest hurdle was that I was using command: "--log-level debug" but that stored the config in /root/ inside the docker container , so every time i recreated the container it would no longer work. Furthermore the root interface on the vlan is set to ipv6 forwarding 0 and accept_ra_rt_info_max_plen 64 as well.

Well done!

So for me at least I no longer set/force `net.ipv6.conf.eth0.accept_ra=1` for the container as this should be its default.  Combined with a default of zero for `net.ipv6.conf.eth0.forwarding` means that you just need to adjust the `.accept_ra_rt_info_max_plen` value as this is what is prohibiting router advertisements from being learned.

Also, for my docker version at least I started getting warning messages about the sysctls syntax being outdated and needing to be "migrated".  You can see the resolved issue thread [here](https://github.com/docker/compose/issues/12508) regarding a change which is percolating through.  Basically I replaced the sysctls stanza with the following...

```
networks:
  iot:
    ipv4_address:  X.Y.A.B
        driver_opts:
            com.docker.network.endpoint.sysctls: net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen=64
```

**Comment by jshoughton** [comment]
I'm struggling to get this working, if I try to create the network with ipv6 bits in it won't create and errors, but if I do it without and ipv4 only it creates the network fine.

this is my network section in my compose file:
```
networks:
 vlan:
    name: vlan
    driver: macvlan
    driver_opts:
      parent: eth0
      com.docker.network.endpoint.sysctls: net.ipv6.conf.IFNAME.accept_ra_rt_info_max_ple>
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/28
          gateway: 192.168.1.254
        #- subnet: fe80:0::/64
        #  gateway: fe80::1
    enable_ipv6: true
```
the error is:

failed to create network vlan: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space

I can get matter-server working fine in host network mode, but then HASS can't communicate with it as it's on macvlan. I can't get HASS to work properly with matter-server as HASS connects to the matter-server but matter-server cannot then connect to matter devices. Any help would be greatly appreciated!

**Comment by ebertek** [comment]
@jshoughton, having `enable_ipv6: true` should be enough, it should assign IPv6 addresses automatically (in my case, it will give the containers sequential IPs from `fd64:<random>:<random>::/64`). If you still want to choose your IPv6 subnet manually, what I found can help with this error message is to restart Docker. :D For some reason removing the network and then trying to deploy it again does not seem to work.
Communication between HAAS and matter-server should work over IPv4 as well. You can remove the Matter integration from HASS, and add it back using `ws://<host-ip>:5580/ws`. If you have issues with communication between the host and your Docker containers using MacVLAN, you can do something like this on your host: `ip link add macvlan0 link eth0 type macvlan mode bridge && ip addr add 192.168.1.1/32 dev macvlan0 && ip link set macvlan0 up && ip route add 192.168.1.0/28 dev macvlan0`.

**Comment by jshoughton** [comment]
@ebertek, thanks, I've reduced it to just having enable_ipv6: true, I took down all containers (using docker compose) then put them up again. Still can't add devices, ipv6 is not my forte!

I already have a very similar command to setup a bridge so that my wireguard container can see the network outside of docker
```
ip link add macvlan-br0 link eth0 type macvlan mode bridge
ip addr add 192.168.1.1/32 dev macvlan-br0
ip link set macvlan-br0 up
ip route add 192.168.1.0/28 dev macvlan-br0
```
if I then use the host ip (192.168.1.1) in HASS matter config it won't recognise it, should I be using a different address within the container?

**Comment by kelvtech-co-uk** [comment]
@jshoughton well done with your update 2 news!

Ref ipv6 in your macvlan network, does your docker host have ipv6 enabled and does your local router too?  My initial attempts to get matter working stumbled over the fact that ipv6 was disabled on both these for me.  And as per @ebertek advise, I just enabled ipv6 and let it resolve addressing itself.

**Comment by pikeas** [comment]
Struggling with this as well. The Matter server errors with:

```
[chip.native.CTL] Discovery timed out
[chip.native.SC] PASESession timed out while waiting for a response from the peer. Expected message type was 33

Config:

```
networks:
    home-lan:
        driver: macvlan
        enable_ipv6: true
        driver_opts:
            parent: eth0
            com.docker.network.endpoint.sysctls: net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen=64
        ipam:
            config:
                - gateway: "..."
                  subnet: ".../24"
                  ip_range: ".../32"

services:
    home-assistant:
        image: ghcr.io/home-assistant/home-assistant:2025.4.2
        volumes:
            - /home/apps/home-assistant:/config
        ports: ["8123:8123"]

    home-assistant-matter:
        image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1
        networks:
            home-lan: { ipv4_address: ... }
        volumes:
            - /home/apps/home-assistant-matter:/data
```

The host has a route to the macvlan so that HA's websocket works, promiscuous mode is enabled on eth0, and there's no firewall.

Matter commissioning works if I use host networking for the Matter server (not needed on the main HA container), so the issue seems scoped to the macvlan setup.

**Comment by kelvtech-co-uk** [comment]
> Struggling with this as well. The Matter server errors with:
> 

Does the matter container get ipv6 interfaces setup correctly when on the macvlan network i.e. is it just the absence of the thread route(s) or is the container not using ipv6 at all when on the macvlan network?

**Comment by ds-sebastian** [comment]
@kelvtech-co-uk I'm trying to get it working on a macvlan on unRAID too. What do you add to your /boot/config/go if anything? Are any of the following necessary:
```
sysctl -w net.ipv4.conf.all.forwarding=1
sysctl -w net.ipv6.conf.all.forwarding=1

 # Using unRAID's default br0 as a macvlan
sysctl -w net.ipv6.conf.br0.accept_ra=2
sysctl -w net.ipv6.conf.br0.accept_ra_rt_info_max_plen=64 
ip6tables -A FORWARD -i br0 -o br0 -j ACCEPT
```

For whatever reason, Matter can only connect to Thread devices if the docker Matter server is on the host network. Matter devices seem to work though

**Comment by kelvtech-co-uk** [comment]
> [@kelvtech-co-uk](https://github.com/kelvtech-co-uk) I'm trying to get it working on a macvlan on unRAID too. What do you add to your /boot/config/go if anything? Are any of the following necessary:
> 
I don't edit/change my unRAID host configuration, if you scan the original post noting the edit/change note at the bottom and then some other posts in this thread I concluded changing the docker host kernel params was redundant (for me at least).

> For whatever reason, Matter can only connect to Thread devices if the docker Matter server is on the host network. Matter devices seem to work though.
> 
> What kind of networking setup did you use for unRAID?

I did need to ensure my internal LAN had IPv6 enabled, this was both on the routing side but also on the unRAID side in the network configuration.  Once this was done the docker containers will then also be issued with IPv6 addresses along with IPv4.  The max_plen kernel parameter needs to be set for the Matter container but thats its. 

If you have a functional Thread network in place then the Matter container should start to accept the route advertisements from your Thread Border Router, this can sometimes take a while to occur after the container has started.

**Comment by sevmonster** [comment]
On modern Linux, modifying kernel tunables isn't required and everything should just work out of the box... At least, they did for me. No clue about Unraid/BSD.

(Well, I don't *think* I've changed any tunables :))

```yml
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    hostname: homeassistant #for mDNS
    restart: unless-stopped
    depends_on:
      - matter-server
    privileged: true #not sure if required
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      #- /run/dbus:/run/dbus:ro
    networks:
      default:
      iot:
        gw_priority:  -1 #make sure gateway is not primary so HA can access the Internet
        mac_address:  aa:aa:aa:aa:aa:aa #set a static address if you want
        ipv4_address: 172.16.0.2 #docker macvlan does not support dhcp, static only
        ipv6_address: fd00:dead:beef::2
    ports:
      - 127.0.0.1:8080:8123 #doesnt work?????? I ended up binding to the docker default network, cant find any documentation on why it doesn't work
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    volumes:
      - ./matter-server:/data
      #- /run/dbus:/run/dbus:ro
    networks:
      default:
      iot:
        gw_priority:  -1
        mac_address:  aa:aa:aa:aa:aa:ab
        ipv4_address: 172.16.0.3
        ipv6_address: fd00:dead:beef::3

networks:
  default:
    # BUG: never gets default gateway with ipv6:
    #      https://github.com/docker/roadmap/issues/658#issuecomment-2864025303
    enable_ipv6: true
  iot:
    driver: macvlan
    driver_opts:
      parent: eth0.100 #driver vlan tagging for macvlan traffic
    enable_ipv6: true
    ipam:
      config:
        - subnet:  172.16.0.0/24
          gateway: 172.16.0.1
        - subnet:  fd00:dead:beef::/64
          gateway: fd00:dead:beef::1
```

My configuration has my server communicating via untagged traffic, while the containers communicate over native Ethernet driver VLAN sub-interfaces. Docker creates and destroys these automatically so this should require no additional setup.

You will of course have to make sure promiscuous mode is enabled on your router for the server's port.

If you use an IPv6 prefix hint for your VLAN's ULA addresses, you'll have to specify it in the subnet, gateway, and IPs. For example, `fd00:dead:beef::/64` with a prefix hint of `100` (to match example VLAN ID) would make `fd00:dead:beef:100::/64`.

The thing that had me tearing my hair out the most about all this was the fact that there is a bug(?) that makes non-IPv6 networks always have lower priority than IPv6-enabled networks for gateway assignment. I didn't have it enabled on my `default` network because I didn't need it, but... I guess I do.

Given all this, I don't think my solution will actually work at all, because I am only just now realizing that `matter-server` does not support using Bluetooth proxies for commissioning. So I may have done all this for nothing. But that's neither here nor there...
